<script setup lang="ts"></script>

<template>
  <div class="flex flex-col  gap-4 max-w-4xl mx-auto px-4 py-40">
    <h1 class="text-4xl fancy">Privacy Policy</h1>
    <div class="roboto text-lg leading-loose">
      <p>
        Primo Sewer Cleaning is committed to protecting your personal information. This Privacy Policy explains how we
        collect,
        use, and safeguard any data you provide when you visit our website.
      </p>
      <p>
        We only collect personally identifiable information when you voluntarily submit it. This may include your name,
        email
        address, or other details you provide through contact forms or other means.
      </p>
      <p>
        Our website uses Google Analytics to help analyze how users interact with our site. Google Analytics uses
        cookies to
        collect standard internet log information and visitor behavior information in an anonymous form. The information
        generated by the cookie about your use of the website (including your IP address) may be transmitted to and
        stored by
        Google. We use this information to evaluate visitors’ usage of the website and to compile statistical reports on
        website
        activity.
      </p>
      <p>
        We do not sell, distribute, or lease your personal information to third parties unless required by law. We may
        update
        this Privacy Policy from time to time. Check this page periodically to ensure you are aware of any changes.
      </p>
    </div>
    <div>
      <ul class="flex flex-col gap-2 mt-4">
        <li>Your data is collected only when voluntarily provided.</li>
        <li>Google Analytics cookies track website usage and performance.</li>
        <li>We do not share personal data without your consent.</li>
        <li>Review this policy regularly for updates or changes.</li>
      </ul>
    </div>
    <div class="mt-4">
      <SharedButton text="See Services" class="max-w-content" />
    </div>
  </div>
</template>

<style scoped></style>
